// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbrepo

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id, token_hash, device_info, ip_address, expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, token_hash, family_id, device_info, ip_address, is_revoked, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID     pgtype.UUID      `json:"user_id"`
	TokenHash  string           `json:"token_hash"`
	DeviceInfo pgtype.Text      `json:"device_info"`
	IpAddress  *netip.Addr      `json:"ip_address"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    rut, dv, email, first_name, last_name, password_hash
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, rut, dv, full_rut, email, first_name, last_name, password_hash, failed_attempts, locked_until, recovery_token, recovery_token_expires_at, is_active, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Rut          int32  `json:"rut"`
	Dv           string `json:"dv"`
	Email        string `json:"email"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Rut,
		arg.Dv,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Rut,
		&i.Dv,
		&i.FullRut,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.RecoveryToken,
		&i.RecoveryTokenExpiresAt,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT pm.role_code, rd.name as role_name
FROM project_members pm
JOIN projects p ON p.id = pm.project_id
JOIN role_definitions rd ON rd.code = pm.role_code
WHERE pm.user_id = $1 
  AND p.project_code = $2 
  AND pm.is_active = TRUE
LIMIT 1
`

type GetProjectMemberParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ProjectCode string      `json:"project_code"`
}

type GetProjectMemberRow struct {
	RoleCode int16  `json:"role_code"`
	RoleName string `json:"role_name"`
}

// Esta es LA clave de tu seguridad (El Portero)
// Verifica si el usuario pertenece al proyecto y devuelve su rol
func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.UserID, arg.ProjectCode)
	var i GetProjectMemberRow
	err := row.Scan(&i.RoleCode, &i.RoleName)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, rut, dv, full_rut, email, first_name, last_name, password_hash, failed_attempts, locked_until, recovery_token, recovery_token_expires_at, is_active, last_login_at, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Rut,
		&i.Dv,
		&i.FullRut,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.RecoveryToken,
		&i.RecoveryTokenExpiresAt,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByRut = `-- name: GetUserByRut :one
SELECT id, rut, dv, full_rut, email, first_name, last_name, password_hash, failed_attempts, locked_until, recovery_token, recovery_token_expires_at, is_active, last_login_at, created_at, updated_at FROM users
WHERE rut = $1 LIMIT 1
`

func (q *Queries) GetUserByRut(ctx context.Context, rut int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByRut, rut)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Rut,
		&i.Dv,
		&i.FullRut,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.RecoveryToken,
		&i.RecoveryTokenExpiresAt,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
