// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbrepo

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64            `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	ProjectID   pgtype.Int4      `json:"project_id"`
	Action      string           `json:"action"`
	Description pgtype.Text      `json:"description"`
	IpAddress   *netip.Addr      `json:"ip_address"`
	UserAgent   pgtype.Text      `json:"user_agent"`
	MetaData    []byte           `json:"meta_data"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Project struct {
	ID          int32            `json:"id"`
	ProjectCode string           `json:"project_code"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	IsActive    pgtype.Bool      `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ProjectMember struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	ProjectID int32            `json:"project_id"`
	RoleCode  int16            `json:"role_code"`
	IsActive  pgtype.Bool      `json:"is_active"`
	JoinedAt  pgtype.Timestamp `json:"joined_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	TokenHash  string           `json:"token_hash"`
	FamilyID   pgtype.UUID      `json:"family_id"`
	DeviceInfo pgtype.Text      `json:"device_info"`
	IpAddress  *netip.Addr      `json:"ip_address"`
	IsRevoked  pgtype.Bool      `json:"is_revoked"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type RoleDefinition struct {
	Code        int16       `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type User struct {
	ID                     pgtype.UUID      `json:"id"`
	Rut                    int32            `json:"rut"`
	Dv                     string           `json:"dv"`
	FullRut                pgtype.Text      `json:"full_rut"`
	Email                  string           `json:"email"`
	FirstName              string           `json:"first_name"`
	LastName               string           `json:"last_name"`
	PasswordHash           string           `json:"password_hash"`
	FailedAttempts         pgtype.Int2      `json:"failed_attempts"`
	LockedUntil            pgtype.Timestamp `json:"locked_until"`
	RecoveryToken          pgtype.Text      `json:"recovery_token"`
	RecoveryTokenExpiresAt pgtype.Timestamp `json:"recovery_token_expires_at"`
	IsActive               pgtype.Bool      `json:"is_active"`
	LastLoginAt            pgtype.Timestamp `json:"last_login_at"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
}
