// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbrepo

import (
	"context"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Esta es LA clave de tu seguridad (El Portero)
	// Verifica si el usuario pertenece al proyecto y devuelve su rol
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByRut(ctx context.Context, rut int32) (User, error)
}

var _ Querier = (*Queries)(nil)
